name: Release

on:
  release:
    types: [created]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
    steps:
      - uses: actions/checkout@main
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

  rpm:
    name: generate rpm package
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: setup cargo
        run: cargo install cargo-generate-rpm

      - name: build release
        run: cargo build --release --bin tutors --manifest-path ./Cargo.toml

      - name: generate rpm package
        run: cargo generate-rpm

      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-musl-rpm
          path: |
            ./target/generate-rpm/tutors-*.rpm
